### ISSUE TITLE
Running the mock UserService in development

### ISSUE THREAD

**Issue by BrianJVarley** [rootstrap/react-native-base#141]
@martinjaimem 
**Is your feature request related to a problem? Please describe.**
Yes kind of, the login and signup screens talk to a User Service. But this mock server isn't included in the repo
in order to run the app.

**Describe the solution you'd like**
Maybe a docker file could be included to spin up this mock User Service that's pointed to in the `.env` files?
For example `https://target-mvd-api.herokuapp.com/api/v1`.

**Describe alternatives you've considered**
I could write my own mock server using Node. But a docker-compose YAML file would be ideal to test out the API basics for me and other adopters of this boilerplate project.

**Additional context**
See: https://github.com/BrianJVarley/react-native-base/blob/1b83db91998175e5f509a195add35c993c4ca3e0/src/services/userService.js

thanks! :)

**Comment by martinjaimem** [comment]
Hi @BrianJVarley we have a backend service for this [here](https://github.com/rootstrap/rails_api_base). It currently supports `docker` so if you follow the instructions there then you shouldn't have any problems. 

As this is a React Native base IMHO it doesn't make much sense to add a backend service here too, but it seems like a good idea to have a link to that backend service in the readme so that everyone can test it locally.

Anyway, feel free to give it a try!

Thanks,
Martin

**Comment by BrianJVarley** [comment]
@martinjaimem thanks, yeah I think a _Running the Mock Service_ README section would be helpful for anyone picking up this repo?
